import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import Navbar from "./navbar";
import { Theme } from "@radix-ui/themes";
import Footer from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tradingview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
    <Theme>
      <Navbar></Navbar>
      <main>{children}</main>
      <Footer background={"bg-black"}></Footer>
    </Theme>
    </>
  );
}
