import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: '%s',
    default: 'Tradingview',
  },
  description: "Generated by create next app",
  keywords: ["financial", "Trade"],

};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={(inter.className, "bg-white  dark:bg-black text-black dark:text-white")}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
