import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "../home/navbar";
import { Theme } from "@radix-ui/themes";


export const metadata: Metadata = {
  title: "Tradingview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Theme>
        <Navbar></Navbar>
        <main>{children}</main>
      </Theme>
    </>
  );
}
